/*
https://dart.dev/guides/language/language-tour#extension-methods
https://www.geeksforgeeks.org/data-enumeration-in-dart/
https://www.educative.io/learn
https://codewithandrea.com/tutorials/
*/
/*
https://dart.dev/guides/language/effective-dart
https://dart.dev/guides/libraries/library-tour
https://dart.dev/guides/language/specifications/DartLangSpec-v2.10.pdf
*/
